### ISSUE TITLE
Error with the watch command

### ISSUE THREAD

**Issue by ydelwiche** [fastly/fastlyctl#8]
From time to time, the command will exit with the following error message:

```
Traceback (most recent call last): Ratio | 0 passes/s | 0 synths/s | 87ms miss time | 0 errors/s
	8: from /usr/local//lib/ruby/gems/2.6.0/bin/fastlyctl:23:in `<main>'
	7: from /usr/local//lib/ruby/gems/2.6.0/bin/fastlyctl:23:in `load'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlyctl-1.0.12/exe/fastlyctl:6:in `<top (required)>'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlyctl-1.0.12/lib/fastlyctl/commands/watch.rb:36:in `watch'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlyctl-1.0.12/lib/fastlyctl/commands/watch.rb:36:in `-': nil can't be coerced into Integer (TypeError)
```

**Comment by carbon198** [comment]
Should be fixed in https://github.com/fastly/fastlyctl/pull/13.
